### ISSUE TITLE
Merge with the official project

### ISSUE THREAD

**Issue by WebBreacher** [Leezj9671/offensiveinterview#1]
Instead of you hosting this in your project and keeping a fork of the original, would you consider changing it so that your files are "knowledge-CN.md" and leaving the original english files alone? That way you can do a pull request and we can add all this hard work you did to the original project.

Unless you wish to keep the project separate, in which case, let me know and I'll link to your version from mine.

**Comment by Leezj9671** [comment]
I did this for the convenience of Chinese users. So they can read Chinese directly. :>
Maybe link my version is better?

**Comment by WebBreacher** [comment]
If that is what you'd like, I'll do that. And thank you for doing this translating!!!!
